baseURL = 'https://tcsw.netlify.app/'
languageCode = 'en-us'
title = 'TCSW'
theme = "hugo-universal-theme"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "de"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false


[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Home"
    url        = "/"
    weight     = 1
    parent     = "menu.home"

[[menu.main]]
    name       = "Über Us"
    url        = "/about/"
    weight     = 2
    parent     = "menu.home"

[[menu.main]]
    name       = "Geschichte"
    url        = "/history/"
    weight     = 3
    parent     = "menu.home"

[[menu.main]]
    name       = "Mitgliedschaften"
    url        = "/membership/"
    weight     = 4
    parent     = "menu.home"

[[menu.main]]
    name       = "Anmeldung"
    url        = "/subscribe/"
    weight     = 5
    parent     = "menu.home"

[[menu.main]]
    name       = "Sponsoren"
    url        = "/sponsors/"
    weight     = 6
    parent     = "menu.home"

[[menu.main]]
    name       = "Dokumente"
    url        = "/documents/documents/"
    weight     = 7
    parent     = "menu.home"

# Main menu
[[menu.main]]
    name       = "Teams"
    identifier = "menu.teams"
    url        = "/teams/"
    weight     = 2

[[menu.main]]
    name       = "Training"
    identifier = "menu.training"
    url        = "/training/"
    weight     = 3

[[menu.main]]
    name       = "ProBase"
    url        = "https://www.tennisprobase.com"
    weight     = 1
    parent     = "menu.training"

[[menu.main]]
    name       = "Platz Reservation"
    url        = "https://apps.gotcourts.com/newplayer/club/clb_11e7461dcc2d76c3a550029843b59922"
    weight     = 2
    parent     = "menu.training"


[[menu.main]]
    name       = "Events"
    identifier = "menu.events"
    url        = "/events/"
    weight     = 4

[[menu.main]]
    name       = "Jahresprogramm"
    url        = "/pdf/jahresprogramm.pdf/"
    weight     = 1
    parent     = "menu.events"


[[menu.main]]
    name       = "ASVZ"
    identifier = "menu.asvz"
    url        = "/asvz/"
    weight     = 5

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6

[[menu.main]]
    name       = "Kontakt"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 7

# Topbar Socials

[[menu.topbar]]
    weight = 1
    name = "Instagram"
    url = "https://instagram.com/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"
    
[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[params]
    style = "red"

    date_format = "2.01.2006"

    disabled_logo = false
    logo_text = "TCSW"
    logo = "img/tcswlogo2-2-1650x1653.png"
    logo_small = "img/tcswlogo2-2-1650x1653.png"

    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>TENNISCLUB SCHÜTZENWIESE</strong>
        <br><strong>Schützenwiesenweg 8, 
        <br>8400 Winterthur, Zürich
        <br><a href="mailto:info@tcsw.ch">info@tcsw.ch</a></strong>
      </p>
      """

[params.static_bg]
    enable = true
    icon = "far fa-file-alt"
    title = "TENNISCLUB SCHÜTZENWIESE"
    subtitle = "WILLKOMMEN BEIM SCHÖNSTEN TENNISCLUB DER STADT WINTERTHUR"
    link_url = "subscribe"
    link_text = "JETZT BEITRETEN"

[params.prices]
    enable = true

[params.features]
    enable = true
    cols = 6 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = false
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.testimonials]
    enable = true
    title = "Vorstand"
    subtitle = "Das Team des Tennisclubs Schützenwiese für die Saison 2023"


[params.clients]
    enable = true
    title = "Unsere Sponsoren"
    subtitle = ""

[params.footer]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

[params.footer.recent_posts]
    enable = true

[params.topbar]
    enable = true